### PR TITLE
paper-textarea on-blur

### LINKED ISSUE #299: Markdown input should render once focus is lost
When the markdown input element loses focus, it should render the markdown

### PR DESCRIPTION
**Pull request by ghost**
Added on-blur event to paper-textarea. It now toggles, and renders markdown, on losing focus.
Fixes #299

### CODE REVIEW

**Review by txsmith — APPROVED** [review]
Looks good! Will test tomorrow.

**Comment by txsmith** [comment]
I'd like to suggest some further improvements to the element:
- When an empty markdown-input loses focus, it should not render because there is not content to render.
- Instead of having to click exactly on the edit button, clicking anywhere on the element should suffice to switch from render to edit mode.

It would be nice if this can all be fixed in the same PR.

**Comment by ghost** [comment]
@txsmith : I think this version does everything you asked. Let me know what you think.

**Comment by txsmith** [comment]
Confirmed working!

**Pull request merged**
