### PR TITLE
Obtain repositories from the user

### LINKED ISSUE #200: Show all users' public & private repos

### PR DESCRIPTION
**Pull request by TimvdLippe**
Fixes #200

### CODE REVIEW

**Comment by eanker** [comment]
image

I only get this repo, whilst that doesnt even excists.
And I have pr's open on our test repo.

**Comment by TimvdLippe** [comment]
@eanker It is actually the only public repository (a fork) you have: 
image

Could you execute a request to https://developer.github.com/v3/repos/#list-your-repositories and check if values are missing?

**Comment by eanker** [comment]
I saw it.
I didnt knew I had forked that one :O

Is it possible to also show the pr's I created?

**Comment by eanker** [comment]
Well, it works.
Unfortunatly, github can not find that I work on preview-code,maybe because we are not a public member.

I have some private repo's but github does not find them, although you get all my repos.

**Comment by TimvdLippe** [comment]
Hm preview-code is included for me and according to the documentation you should too:

> This includes repositories owned by the authenticated user, repositories where the authenticated user is a collaborator, and repositories that the authenticated user has access to through an organization membership.

**Comment by eanker** [comment]
Yes, I see.
It just does not show for me, even if I add `affiliation=organization_member` altough that's default included.
But the github API itself does not include them for me.

**Comment by eanker** [comment]
I found the problem.
If I use a token that has access to everything, it works.
The normal api key has not enough permissions for me.

This might be the same problem as I get with using #215.
So, I need a way to get the right permissions on my key.

**Comment by TimvdLippe** [comment]
@eanker Yes you should. It should be fixed with https://github.com/preview-code/rite-evaluation/pull/214/files#diff-6fd0e8ea1b60056730e08697d813c1c0R106

**Comment by eanker** [comment]
LGTM,
Travis fails, but otherwise good to merge.

**Comment by TimvdLippe** [comment]
Travis has been fixed :tada:

**Pull request merged**
