### PR TITLE
Filtering and searching

### PR DESCRIPTION
**Pull request by eanker**
image

You can search trough projects and pull requests on name and title.

### CODE REVIEW

**Comment by txsmith** [comment]
The PR list seems to be scrolling in the wrong way.
Also, filtering should not change the list width.
Maybe a rebase will help?

**Comment by eanker** [comment]
Rebase did not help, will look into it.

**Comment by eanker** [comment]
Fixed, do we need a last item in the pr list, so that it's more clear the list is empty?

**Comment by txsmith** [comment]
Yes that would be nice.

However, your last commit does not seem to fix things entirely:
screenshot from 2016-05-11 13 10 50

The search and filter bar should be above the list. Maybe you can put those elements inside the list so they appear as the first list item.

**Comment by txsmith** [comment]
I also notice a `test` debug statement being printed to the console.

**Comment by eanker** [comment]
Oops, I had first changed the position and then verified.
Deleted that and tought I verified, but it probably hadn't reloaded.
Will fix.

**Comment by txsmith** [comment]
Verified fixes, it looks good!

**Pull request merged**
