### PR TITLE
graceful-api-error-handling

### PR DESCRIPTION
**Pull request by ghost**
I think this is the best way to achieve a notification with the least
amount of code. I tried others (e.g. have the ajax components create
the toast) but they were all cumbersome.

I've added an event firing specific to this toast to the error-handling of the ajax components.

The coded is linted and tested.

### CODE REVIEW

**Comment by eanker** [comment]
I think the way you implemented it is good.
Only I would suggest changing the error message of the github API.
There I would mention that we cannot connect to github.

**Comment by eanker** [comment]
Fixes #386

**Review by txsmith — CHANGES_REQUESTED** [review]
The error message should be improved to inform the user which action went wrong (placing a comment, fetching diffs, etc) and where this went wrong (call to github, or firebase/backend?)

**Comment by txsmith** [comment]
Also, please rebase with master to resolve conflicts

**Comment by ghost** [comment]
Apologies: I have no idea how the conflict occured. I am sure I had updated from master before I commited to the branch. If you have any ideas / suspicions, please let me know so that I can avoid this in the future. Again, apologies.

I have now merged from master (locally), and I have resolved the conflicts - but I can't login anymore.

screen shot 2016-10-26 at 09 24 03

I'll check my merges again. If I can't solve this on my own, I'll get back to you.

**Comment by ghost** [comment]
Regarding the error message: thanks for the feedback. I'll implement what you say as soon as I have resolved my auth issue.

**Comment by ghost** [comment]
Apparently I can now login again so, please, disregard above issue.

**Comment by ghost** [comment]
I believe it's ready. Please have another look and let me know what you think. :bowtie::see_no_evil:

**Comment by eanker** [comment]
I see a lot more information is available for the user.
As the user is a programmer it should be able to understand the data, only it is there to short to really read i tall.
However I feel like it's a bit too much (detailed) information.
As they are not developing the website, they are just using it.
Maybe we just need to specify were the API is located and that's enough.

@txsmith Can you tell us (quickly) what you think.

The code itself looks fine.

**Pull request closed without merging**
