### PR TITLE
Polymer build v2

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR replaces the old gulp file with the new `polymer-build`.

To generate a build, run `npm run build`.
To serve locally run `polymer serve`
To serve the build run `polymer serve build/unbundled`

You will need to `npm install -g polymer-cli`, run `npm install` for all the new dependencies and delete `src/bower_components` and run `bower install` again to install in the new location.
The bower folder had to be changed to not parse all dependencies (and its documentation) with `polymer-build` to prevent it crashing 😄 

For some reason locally I was not getting logged in with Firebase. After the redirect the `document.referrer` was empty. Probably replacing the redirect with a popup solves a lot of issues.

### CODE REVIEW

**Comment by eanker** [comment]
When I run the new version I get:
image

It seems serviceworker doesn't work, is there some command I should execute?

**Comment by eanker** [comment]
The issue with the non-redirect is caused by the polymer-cli in combination with firebase.
Therefore the navigateFallbackWhitelist in sw-precache-config.json should be set.
However, I cannot seem to get it to work, as the regex is not parsed correctly on build.
You can verify this by viewing the generated service-worker.js file and checking that 
`isPathWhitelisted([null], event.request.url))` the null is changed to the regex.
In the .js version it should be `navigateFallbackWhitelist: [/^(?!\/__)/]` or `navigateFallbackWhitelist: [ /^\/project\// ]`.

**Comment by TimvdLippe** [comment]
Reminder to me: refactor the firebase authentication to a popup login

**Comment by TimvdLippe** [comment]
@eanker PTAL :smile:

**Comment by TimvdLippe** [comment]
Never mind, still need to fix an issue when you are already logged in

**Pull request merged**
