### PR TITLE
Extract reusable list item

### PR DESCRIPTION
**Pull request by txsmith**
screenshot from 2016-05-03 12 09 24

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Reviewed IRL. Some small CSS comments and some indentation. Also moved the list item elements to a separate folder for generic usage. LGTM after applied changes.

**Comment by eanker** [comment]
The result looks very nice.
LGTM

**Comment by eanker** [comment]
The styling has been broken since the last commit.

**Comment by eanker** [comment]
LGTM

**Comment by TimvdLippe** [comment]
LGTM!

**Pull request merged**
