### PR TITLE
Add gulp serve command and fix directories

### PR DESCRIPTION
**Pull request by TimvdLippe**
You can now run `gulp serve` to serve the application. Whenever you make a change in `src/` it will automatically refresh the page.

Make sure to `npm install` the dependencies. You also have to move the `bower_components` folder from `/` to `src/` to resolve all relative paths in the elements.

Also enabled shadow dom and lazyRegister as performance optimization.

### CODE REVIEW

**Comment by txsmith** [comment]
What npm dependencies should we install?

**Comment by txsmith** [comment]
Small bug, given you are at the projects page,
when you select a project
and click `MY PULL REQUESTS`
and then click `MY PROJECTS`
the selected previously selected project does not become unselected.

**Comment by txsmith** [comment]
Looks good!

**Comment by eanker** [comment]
Works as expected. Good to merge.

**Pull request merged**
