### PR TITLE
Let pull request page use real data

### PR DESCRIPTION
**Pull request by TimvdLippe**
image

### CODE REVIEW

**Comment by txsmith** [comment]
I cannot merge this yet because the reviewer list and comments are still missing and these need to be present in the prototype.

**Comment by TimvdLippe** [comment]
Comments and reviewer added again. Check out http://localhost:5200/projects/Polymer/Polymer/pulls/3630/overview to test all the features. Also supports user mentions and clickable issues.

**Comment by txsmith** [comment]
I do not see reviewers in any PR. It also seems like te `changes` view is broken

**Comment by TimvdLippe** [comment]
image
Image of the above linked pull request. To the right you can see the image of the reviewer.

**Comment by txsmith** [comment]
Verified to work, let's merge

**Pull request merged**
