### PR TITLE
Extract marked-github-element and fix issue with code highlighting

### PR DESCRIPTION
**Pull request by TimvdLippe**
Extracted an element out of the behavior to prevent duplicate styling. Also fixed code highlighting.

image

The `on-error` is an inline code block which has no class. Therefore it will receive a background. All multi-line code blocks are wrapped inside a `<pre>` which also have a class. Therefore they have `background-color: #f7f7f7`. These are the colors used by GitHub.

### CODE REVIEW

**Comment by eanker** [comment]
@ and # aren't rendered as links, so they are not clickable is that intended?
Or is that out of scope of this pr.

**Comment by TimvdLippe** [comment]
Oops forgot to mention you must rerun `bower update` to fetch my forked version `marked-element` which exposes the `callback` property.

**Comment by eanker** [comment]
In "Fix conditions when dom-repeat needs to re-sort or re-filter." from kaste in Polymer/Polymer the `item.#2` is rendered as `item.`[2](url) Can we only make #'s click-able when they have a space in front or such?

**Comment by eanker** [comment]
LGTM

**Pull request merged**
