### PR TITLE
Change info-header to feature-bar

### PR DESCRIPTION
**Pull request by txsmith**
This is to save space and make layout easier with space view

---

Review this pull request [on Preview Code](https://preview-code.com/projects/preview-code/frontend/pulls/390/overview).

### CODE REVIEW

**Comment by eanker** [comment]
Works as intended, except for my comment below.

**Comment by eanker** [comment]
image
This part does not look so good as of now.

**Comment by txsmith** [comment]
I intend to fix this as part of a separate PR since this one is already getting large

**Comment by eanker** [comment]
As the pull request is comming soon, I'll merge it.

**Pull request merged**
