### PR TITLE
Fix list navigation with less code :tada:

### LINKED ISSUE #185: Lists should be collapsed when not navigating in projects
When you open a specific pull-request or create a pull request, the lists are both collapsed. They should be uncollapsed, to have more space for the actual view (and have 1 less click to actually see what you want). Probably we need to refactor the logic a bit too.

### PR DESCRIPTION
**Pull request by TimvdLippe**
Fixes #185

### CODE REVIEW

**Comment by eanker** [comment]
Can you fix the tests, this might be due to the fact that you changed the elements for the methods.
Altough the functionality looks good.

**Comment by TimvdLippe** [comment]
Removed the tests, as these properties were removed.

**Comment by eanker** [comment]
Wouldn't it be better to keep the test, but change them and put them in the correct file.
The functionality stays the same, and so are the showPullList and showProjectlList properties.
Even the selectedPull and seletedProject are still there, so I don't see why these test need to be removed.

**Comment by TimvdLippe** [comment]
Added them back to projects-page

**Comment by eanker** [comment]
LGTM

**Comment by txsmith** [comment]
This was merged but it does not work. Clicking anywhere in the shadow area does not collapse the lists anymore. Any idea why this is broken?

**Comment by TimvdLippe** [comment]
Hm I tested this and it worked. I will retest tomorrow then to see what broke.

**Comment by TimvdLippe** [comment]
#191 is up

**Pull request merged**
